-- robert/semantic/rust.lua
--
-- rust-analyzer semantic token → Tree-sitter / colorscheme bridge
-- Generated by ChatGPT from rust-analyzer semantic tokens taxonomy
-- Safe to apply after :colorscheme

local M = {}

M.links = {
	-- =====================
	-- Core symbols
	-- =====================
	["@lsp.type.function.rust"] = "@function",
	["@lsp.type.method.rust"] = "@method",
	["@lsp.type.macro.rust"] = "@macro",
	["@lsp.type.proc_macro.rust"] = "@macro",
	["@lsp.type.variable.rust"] = "@variable",
	["@lsp.type.parameter.rust"] = "@parameter",
	["@lsp.type.property.rust"] = "@property",
	["@lsp.type.field.rust"] = "@field",

	-- =====================
	-- Types
	-- =====================
	["@lsp.type.struct.rust"] = "@type",
	["@lsp.type.enum.rust"] = "@type",
	["@lsp.type.union.rust"] = "@type",
	["@lsp.type.trait.rust"] = "@type",
	["@lsp.type.typeAlias.rust"] = "@type",
	["@lsp.type.typeParameter.rust"] = "@typeParameter",
	["@lsp.type.enumMember.rust"] = "@constant",
	["@lsp.type.builtinType.rust"] = "@type.builtin",

	-- =====================
	-- Constants / statics
	-- =====================
	["@lsp.type.constant.rust"] = "@constant",
	["@lsp.type.constParameter.rust"] = "@constant",
	["@lsp.type.static.rust"] = "@constant",

	-- =====================
	-- Modules / namespaces
	-- =====================
	["@lsp.type.module.rust"] = "@module",
	["@lsp.type.namespace.rust"] = "@module",

	-- =====================
	-- Keywords / control
	-- =====================
	["@lsp.type.keyword.rust"] = "@keyword",
	["@lsp.type.label.rust"] = "@label",
	["@lsp.type.lifetime.rust"] = "@keyword",

	-- =====================
	-- Literals
	-- =====================
	["@lsp.type.string.rust"] = "@string",
	["@lsp.type.number.rust"] = "@number",
	["@lsp.type.boolean.rust"] = "@boolean",
	["@lsp.type.character.rust"] = "@character",

	-- =====================
	-- Operators / punctuation
	-- =====================
	["@lsp.type.operator.rust"] = "@operator",
	["@lsp.type.punctuation.rust"] = "@punctuation",

	-- =====================
	-- Attributes / derives
	-- =====================
	["@lsp.type.attribute.rust"] = "@attribute",
	["@lsp.type.builtinAttribute.rust"] = "@attribute",
	["@lsp.type.derive.rust"] = "@macro",
	["@lsp.type.deriveHelper.rust"] = "@macro",

	-- =====================
	-- Error-ish
	-- =====================
	["@lsp.type.unresolvedReference.rust"] = "@error",

	-- =====================
	-- Modifiers
	-- =====================
	["@lsp.mod.declaration.rust"] = "@function",
	["@lsp.mod.definition.rust"] = "@function",
	["@lsp.mod.readonly.rust"] = "@constant",
	["@lsp.mod.mutable.rust"] = "@variable",
	["@lsp.mod.static.rust"] = "@constant",
	["@lsp.mod.async.rust"] = "@keyword",
	["@lsp.mod.unsafe.rust"] = "@error",
	["@lsp.mod.trait.rust"] = "@type",
	["@lsp.mod.public.rust"] = "@keyword",
	["@lsp.mod.defaultLibrary.rust"] = "@function.builtin",
	["@lsp.mod.documentation.rust"] = "@comment",
	["@lsp.mod.deprecated.rust"] = "DiagnosticDeprecated",

	-- =====================
	-- Type + modifier combos (high priority)
	-- =====================
	["@lsp.typemod.function.declaration.rust"] = "@function",
	["@lsp.typemod.method.declaration.rust"] = "@method",
	["@lsp.typemod.variable.mutable.rust"] = "@variable",
	["@lsp.typemod.variable.readonly.rust"] = "@constant",
	["@lsp.typemod.type.defaultLibrary.rust"] = "@type.builtin",

	-- =====================
	-- Nuclear fallback
	-- =====================
	-- If this is undefined, everything turns gray
	--["@lsp"] = "@variable",
}

function M.apply()
	local hl = vim.api.nvim_set_hl

	for from, to in pairs(M.links) do
		hl(0, from, { link = to })
	end

	-- Optional: do not gray out unused code
	hl(0, "DiagnosticUnnecessary", { link = "Normal" })
end

return M
